import { Transaction, Category } from './types';

export const CATEGORIES: Category[] = [
  'Food',
  'Rent',
  'Salary',
  'Entertainment',
  'Transport',
  'Utilities',
  'Misc',
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    date: '2024-03-01',
    amount: 5000,
    category: 'Salary',
    type: 'income',
    notes: 'Monthly paycheck',
  },
  {
    id: '2',
    date: '2024-03-02',
    amount: 1200,
    category: 'Rent',
    type: 'expense',
    notes: 'March rent',
  },
  {
    id: '3',
    date: '2024-03-05',
    amount: 150,
    category: 'Food',
    type: 'expense',
    notes: 'Grocery shopping',
  },
  {
    id: '4',
    date: '2024-03-10',
    amount: 80,
    category: 'Transport',
    type: 'expense',
    notes: 'Fuel refill',
  },
  {
    id: '5',
    date: '2024-03-15',
    amount: 200,
    category: 'Entertainment',
    type: 'expense',
    notes: 'Movie night & dinner',
  },
  {
    id: '6',
    date: '2024-03-18',
    amount: 120,
    category: 'Utilities',
    type: 'expense',
    notes: 'Electricity bill',
  },
  {
    id: '7',
    date: '2024-03-20',
    amount: 300,
    category: 'Misc',
    type: 'expense',
    notes: 'New desk lamp',
  },
  {
    id: '8',
    date: '2024-03-22',
    amount: 45,
    category: 'Food',
    type: 'expense',
    notes: 'Lunch with friends',
  },
  {
    id: '9',
    date: '2024-03-25',
    amount: 1500,
    category: 'Salary',
    type: 'income',
    notes: 'Freelance project bonus',
  },
  {
    id: '10',
    date: '2024-03-28',
    amount: 60,
    category: 'Transport',
    type: 'expense',
    notes: 'Bus pass renewal',
  },
];
